import { useEffect, useMemo, useState } from 'react';
import {
  Activity, BarChart3, Bell, Bike, BookOpen, CalendarDays, ChevronRight, CircleDollarSign,
  Clock3, Coffee, CookingPot, CreditCard, Flame, LayoutDashboard, Menu as MenuIcon, MoreHorizontal,
  Plus, Search, Settings, ShieldCheck, Sparkles, Tag, Ticket, UserRound, UsersRound, Utensils,
  X, Check, ArrowUpRight, CircleAlert, ChefHat
} from 'lucide-react';
import { serviceApi } from './services/api';

const menuSeed = [
  { id: 1, name: 'Charred citrus salmon', category: 'Mains', price: 28, status: 'Live', accent: 'coral', description: 'Fennel, burnt orange, saffron broth', image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=700&q=80' },
  { id: 2, name: 'Wild mushroom toast', category: 'Small plates', price: 15, status: 'Live', accent: 'sage', description: 'Sourdough, whipped ricotta, thyme', image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?auto=format&fit=crop&w=700&q=80' },
  { id: 3, name: 'Ember house burger', category: 'Mains', price: 21, status: 'Live', accent: 'amber', description: 'Aged cheddar, pickled shallot, jus', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80' },
  { id: 4, name: 'Olive oil cake', category: 'Desserts', price: 11, status: 'Live', accent: 'plum', description: 'Meyer lemon, crème fraîche', image: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=700&q=80' },
  { id: 5, name: 'Garden tonic', category: 'Drinks', price: 9, status: 'Draft', accent: 'teal', description: 'Cucumber, basil, green apple', image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=700&q=80' },
  { id: 6, name: 'Smoked tomato rigatoni', category: 'Mains', price: 19, status: 'Live', accent: 'red', description: 'Pecorino, chilli, basil oil', image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=700&q=80' }
];

const navGroups = [
  { label: 'Workspace', items: [['dashboard', 'Overview', LayoutDashboard], ['orders', 'Orders', Ticket], ['kitchen', 'Kitchen', ChefHat], ['reservations', 'Reservations', CalendarDays]] },
  { label: 'Growth', items: [['menu', 'Menu studio', Utensils], ['customers', 'Customers', UsersRound], ['promotions', 'Promotions', Tag], ['analytics', 'Analytics', BarChart3]] },
  { label: 'Operations', items: [['delivery', 'Delivery', Bike], ['settings', 'Settings', Settings]] }
];

const titles = { dashboard: ['Good morning, Maya', 'Here is the pulse of Ember Table today.'], orders: ['Order flow', 'Keep every ticket moving with clarity.'], kitchen: ['Kitchen display', 'A calm pass makes a memorable service.'], reservations: ['Reservations', 'Shape the room before guests arrive.'], menu: ['Menu studio', 'Curate what guests crave next.'], customers: ['Guest book', 'Relationships are the best regular.'], promotions: ['Promotions', 'Give the right guest a reason to return.'], analytics: ['Analytics', 'Small signals. Better decisions.'], delivery: ['Delivery desk', 'Every handoff, beautifully timed.'], settings: ['Settings', 'Tune the way your restaurant runs.'] };

function App() {
  const [page, setPage] = useState(window.location.hash.slice(1) || 'dashboard');
  const [menu, setMenu] = useState(menuSeed);
  const [orders, setOrders] = useState([{ id: '#1048', guest: 'Noah Williams', table: 'T-04', items: 3, total: 84, status: 'Preparing', time: '2 min ago' }, { id: '#1047', guest: 'Amelia Chen', table: 'Delivery', items: 2, total: 48, status: 'Ready', time: '8 min ago' }, { id: '#1046', guest: 'Liam Foster', table: 'T-08', items: 4, total: 112, status: 'Served', time: '16 min ago' }, { id: '#1045', guest: 'Sofia Patel', table: 'Pickup', items: 1, total: 21, status: 'New', time: '20 min ago' }]);
  const [reservations, setReservations] = useState([{ name: 'Maya Rodriguez', time: '7:00 PM', guests: 4, table: 'Table 12', status: 'Seated' }, { name: 'Noah Williams', time: '7:30 PM', guests: 2, table: 'Table 04', status: 'Confirmed' }, { name: 'Evelyn Brooks', time: '8:00 PM', guests: 6, table: 'Table 18', status: 'Confirmed' }]);
  const [customers, setCustomers] = useState([{ name: 'Amelia Chen', visits: 18, spent: '$1,240', tag: 'Regular' }, { name: 'Noah Williams', visits: 7, spent: '$438', tag: 'New this month' }, { name: 'Maya Rodriguez', visits: 12, spent: '$876', tag: 'VIP' }]);
  const [toast, setToast] = useState('');
  const [serviceOnline, setServiceOnline] = useState(false);
  useEffect(() => { serviceApi.health().then(() => setServiceOnline(true)).catch(() => setServiceOnline(false)); }, []);
  const go = (next) => { setPage(next); window.history.replaceState(null, '', `#${next}`); };
  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(''), 2600); };
  const updateOrder = (id) => { setOrders((current) => current.map((order) => order.id === id ? { ...order, status: order.status === 'New' ? 'Preparing' : order.status === 'Preparing' ? 'Ready' : 'Served' } : order)); notify('Order status updated'); };

  return <div className="app-shell">
    <Sidebar page={page} go={go} />
    <main className="main-column">
      <header className="topbar"><div className="crumb"><span>Ember Table</span><ChevronRight size={14} /><strong>{titles[page]?.[0] || 'Overview'}</strong></div><div className="top-actions"><div className="service-status"><span className={serviceOnline ? '' : 'offline'}></span> {serviceOnline ? 'Service is smooth' : 'Service check pending'}</div><button className="round-button" onClick={() => notify('You are all caught up')} aria-label="Notifications"><Bell size={18} /><i></i></button><div className="profile"><div className="avatar">MR</div><div><strong>Maya Rhodes</strong><small>General manager</small></div><ChevronRight size={14} /></div></div></header>
      <div className="page-heading"><div><p className="eyebrow">{page === 'dashboard' ? 'Tuesday, September 23, 2026' : 'EMBER TABLE / OPERATIONS'}</p><h1>{titles[page]?.[0]}</h1><p className="subtitle">{titles[page]?.[1]}</p></div><QuickAction page={page} go={go} notify={notify} /></div>
      {page === 'dashboard' && <Dashboard go={go} orders={orders} reservations={reservations} />}
      {page === 'orders' && <Orders orders={orders} updateOrder={updateOrder} />}
      {page === 'kitchen' && <Kitchen orders={orders} updateOrder={updateOrder} />}
      {page === 'reservations' && <Reservations reservations={reservations} setReservations={setReservations} notify={notify} />}
      {page === 'menu' && <MenuStudio menu={menu} setMenu={setMenu} notify={notify} />}
      {page === 'customers' && <Customers customers={customers} setCustomers={setCustomers} notify={notify} />}
      {page === 'promotions' && <Promotions notify={notify} />}
      {page === 'analytics' && <Analytics />}
      {page === 'delivery' && <Delivery notify={notify} />}
      {page === 'settings' && <SettingsPage notify={notify} />}
      <footer><span>Ember Table</span><span>Made for thoughtful service</span><span>v1.0.0</span></footer>
    </main>
    {toast && <div className="toast"><Check size={17} />{toast}</div>}
  </div>;
}

function Sidebar({ page, go }) { return <aside className="sidebar"><div className="brand"><div className="brand-mark"><Flame size={19} fill="currentColor" /></div><div><strong>ember</strong><small>table / os</small></div></div><div className="venue-switch"><div className="venue-icon"><Coffee size={17} /></div><div><span>Current venue</span><strong>Ember Table</strong></div><MoreHorizontal size={17} /></div><nav>{navGroups.map((group) => <div className="nav-group" key={group.label}><label>{group.label}</label>{group.items.map(([key, label, Icon]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => go(key)}><Icon size={17} /><span>{label}</span>{key === 'orders' && <em>4</em>}</button>)}</div>)}</nav><div className="sidebar-foot"><div className="help-card"><Sparkles size={17} /><strong>Need a hand?</strong><p>Our service team is one tap away.</p><button onClick={() => go('settings')}>Open support <ArrowUpRight size={14} /></button></div><div className="user-mini"><div className="avatar small">MR</div><div><strong>Maya Rhodes</strong><small>Admin access</small></div><Settings size={16} /></div></div></aside>; }

function QuickAction({ page, go, notify }) { if (page === 'dashboard') return <button className="primary-button" onClick={() => go('orders')}><Plus size={17} /> New order</button>; if (page === 'menu') return <button className="primary-button" onClick={() => notify('Menu item composer opened')}><Plus size={17} /> Add item</button>; if (page === 'reservations') return <button className="primary-button" onClick={() => notify('Reservation form opened')}><Plus size={17} /> New reservation</button>; return <button className="quiet-button" onClick={() => notify('Report exported')}><Activity size={16} /> Export report</button>; }

function Dashboard({ go, orders, reservations }) { return <><div className="stats-row"><Stat icon={CircleDollarSign} label="Today's revenue" value="$4,286" delta="18.4%" tone="green" /><Stat icon={Ticket} label="Open orders" value="24" delta="6.8%" tone="orange" /><Stat icon={CalendarDays} label="Reservations" value="38" delta="12.2%" tone="blue" /><Stat icon={UsersRound} label="Guest rating" value="4.9" delta="0.2" tone="pink" /></div><div className="content-grid dashboard-grid"><section className="panel revenue-panel"><PanelHead title="Revenue overview" action="Last 7 days" /><div className="revenue-total"><strong>$24,681</strong><span><ArrowUpRight size={14} /> 14.8% <small>vs. last week</small></span></div><RevenueChart /></section><section className="panel service-panel"><PanelHead title="Service pulse" action="Live" /><div className="pulse-list"><Pulse label="Tables occupied" value="18 / 26" progress={69} color="coral" /><Pulse label="Average ticket time" value="18 min" progress={78} color="amber" /><Pulse label="Guest satisfaction" value="94%" progress={94} color="sage" /></div><div className="next-shift"><div className="shift-icon"><Clock3 size={16} /></div><div><small>Next shift starts in</small><strong>1h 24m <span>• 6 team members</span></strong></div></div></section><section className="panel recent-panel"><PanelHead title="Recent orders" action="View all" onAction={() => go('orders')} /><OrderTable orders={orders.slice(0, 4)} compact /></section><section className="panel reservation-panel"><PanelHead title="Tonight's table" action="Manage" onAction={() => go('reservations')} /><div className="table-visual"><div className="table-ring"><strong>38</strong><span>covers</span></div><div className="table-legend"><span><i className="dot coral"></i> Seated <b>12</b></span><span><i className="dot sage"></i> Confirmed <b>20</b></span><span><i className="dot pale"></i> Available <b>6</b></span></div></div><div className="mini-reservations">{reservations.slice(0, 2).map((item) => <div key={item.name}><div className="avatar tiny">{item.name.split(' ').map((n) => n[0]).join('')}</div><span><strong>{item.name}</strong><small>{item.time} · {item.guests} guests</small></span><b>{item.status}</b></div>)}</div></section></div></>; }

function Stat({ icon: Icon, label, value, delta, tone }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={18} /></div><span>{label}</span><strong>{value}</strong><small className={tone}><ArrowUpRight size={12} /> {delta} <em>this week</em></small></div>; }
function PanelHead({ title, action, onAction }) { return <div className="panel-head"><h2>{title}</h2><button onClick={onAction}>{action} <ChevronRight size={14} /></button></div>; }
function Pulse({ label, value, progress, color }) { return <div className="pulse"><div><span>{label}</span><strong>{value}</strong></div><div className="progress"><i className={color} style={{ width: `${progress}%` }}></i></div></div>; }
function RevenueChart() { return <div className="chart"><div className="chart-y"><span>$5k</span><span>$3k</span><span>$1k</span><span>$0</span></div><div className="chart-bars">{[42, 58, 47, 76, 63, 88, 71].map((height, index) => <div key={height} className="bar-wrap"><div className={`bar ${index === 5 ? 'highlight' : ''}`} style={{ height: `${height}%` }}><span>${[2.1, 2.9, 2.4, 3.7, 3.1, 4.4, 3.6][index]}k</span></div><small>{['Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Mon', 'Tue'][index]}</small></div>)}</div></div>; }
function OrderTable({ orders, compact }) { return <div className="order-table">{orders.map((order) => <div className="order-row" key={order.id}><div className="order-number"><strong>{order.id}</strong><small>{order.time}</small></div><div className="order-guest"><div className="avatar tiny">{order.guest.split(' ').map((n) => n[0]).join('')}</div><span><strong>{order.guest}</strong><small>{order.table} · {order.items} items</small></span></div><strong>${order.total}</strong><Status value={order.status} /></div>)}</div>; }
function Status({ value }) { return <span className={`status ${value.toLowerCase()}`}><i></i>{value}</span>; }

function Orders({ orders, updateOrder }) { const [filter, setFilter] = useState('All orders'); return <div className="stack"><div className="filter-bar"><div className="tabs">{['All orders', 'New', 'Preparing', 'Ready', 'Served'].map((tab) => <button className={filter === tab ? 'selected' : ''} onClick={() => setFilter(tab)} key={tab}>{tab}</button>)}</div><div className="filter-search"><Search size={16} /><input placeholder="Search orders" /></div></div><section className="panel full-panel"><div className="table-heading"><div><h2>Live order queue</h2><p>All service channels, one clear view.</p></div><span className="live-label"><i></i> Updating live</span></div><OrderTable orders={filter === 'All orders' ? orders : orders.filter((order) => order.status === filter)} /><div className="table-actions">{orders.filter((order) => order.status !== 'Served').slice(0, 2).map((order) => <button onClick={() => updateOrder(order.id)} key={order.id}>Advance {order.id} <ArrowUpRight size={14} /></button>)}</div></section></div>; }
function Kitchen({ orders, updateOrder }) { return <div className="kitchen-board"><div className="kitchen-column"><div className="column-head"><span className="orange-dot"></span><h2>New tickets</h2><b>{orders.filter((o) => o.status === 'New').length}</b></div>{orders.filter((o) => o.status === 'New').map((o) => <KitchenTicket order={o} updateOrder={updateOrder} />)}<EmptyState label="No new tickets" /></div><div className="kitchen-column active-column"><div className="column-head"><span className="yellow-dot"></span><h2>On the pass</h2><b>{orders.filter((o) => o.status === 'Preparing').length}</b></div>{orders.filter((o) => o.status === 'Preparing').map((o) => <KitchenTicket order={o} updateOrder={updateOrder} />)}<EmptyState label="Pass is clear" /></div><div className="kitchen-column"><div className="column-head"><span className="green-dot"></span><h2>Ready to run</h2><b>{orders.filter((o) => o.status === 'Ready').length}</b></div>{orders.filter((o) => o.status === 'Ready').map((o) => <KitchenTicket order={o} updateOrder={updateOrder} />)}<EmptyState label="Nothing waiting" /></div></div>; }
function KitchenTicket({ order, updateOrder }) { return <article className="kitchen-ticket"><div><strong>{order.id}</strong><span>{order.time}</span></div><h3>{order.guest}</h3><ul><li>{order.items} items</li><li>{order.table}</li></ul><button onClick={() => updateOrder(order.id)}>Move forward <ChevronRight size={14} /></button></article>; }
function EmptyState({ label }) { return <div className="empty-state"><CookingPot size={20} /><span>{label}</span></div>; }

function Reservations({ reservations, setReservations, notify }) { const [view, setView] = useState('Today'); const [name, setName] = useState(''); const add = (event) => { event.preventDefault(); if (!name) return; setReservations((current) => [...current, { name, time: '8:30 PM', guests: 2, table: 'Table 09', status: 'Confirmed' }]); setName(''); notify('Reservation added to the book'); }; return <div className="content-grid reservation-page"><section className="panel full-panel"><div className="calendar-top"><div className="tabs">{['Today', 'Tomorrow', 'This week'].map((tab) => <button className={view === tab ? 'selected' : ''} onClick={() => setView(tab)} key={tab}>{tab}</button>)}</div><div className="calendar-date"><ChevronRight size={15} className="back" /> Tuesday, Sep 23 <ChevronRight size={15} /></div></div><div className="timeline">{['5:30 PM', '6:00 PM', '6:30 PM', '7:00 PM', '7:30 PM', '8:00 PM', '8:30 PM', '9:00 PM'].map((time) => <div className="time-row" key={time}><span>{time}</span><div>{reservations.filter((r) => r.time === time).map((r) => <div className="reservation-chip" key={r.name}><div className="avatar tiny">{r.name.split(' ').map((n) => n[0]).join('')}</div><strong>{r.name}</strong><small>{r.guests} guests · {r.table}</small><Status value={r.status} /></div>)}</div></div>)}</div></section><section className="panel add-reservation"><PanelHead title="Quick add" action="" /><form onSubmit={add}><label>Guest name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Jordan Lee" /></label><label>Party size<select><option>2 guests</option><option>4 guests</option><option>6 guests</option></select></label><button className="primary-button" type="submit"><Plus size={16} /> Add reservation</button></form><div className="reservation-note"><CalendarDays size={17} /><span><strong>38 covers booked</strong><small>62% of tonight's capacity</small></span></div></section></div>; }

function MenuStudio({ menu, setMenu, notify }) { const [query, setQuery] = useState(''); const filtered = menu.filter((item) => item.name.toLowerCase().includes(query.toLowerCase())); return <div className="stack"><div className="filter-bar"><div className="category-pills"><button className="selected">All items <b>{menu.length}</b></button><button>Small plates</button><button>Mains</button><button>Drinks</button><button>Desserts</button></div><div className="filter-search"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Find a dish" /></div></div><div className="menu-grid">{filtered.map((item) => <article className="menu-card" key={item.id}><img src={item.image} alt="" /><div className="menu-card-body"><div className="menu-card-head"><span className={`food-accent ${item.accent}`}></span><span className={`status ${item.status.toLowerCase()}`}><i></i>{item.status}</span></div><h2>{item.name}</h2><p>{item.description}</p><div><strong>${item.price}</strong><button onClick={() => { setMenu((current) => current.map((dish) => dish.id === item.id ? { ...dish, status: dish.status === 'Live' ? 'Draft' : 'Live' } : dish)); notify(`${item.name} status updated`); }}>{item.status === 'Live' ? 'Unpublish' : 'Publish'}</button></div></div></article>)}</div></div>; }

function Customers({ customers, setCustomers, notify }) { const [name, setName] = useState(''); return <div className="content-grid customer-grid"><section className="panel full-panel"><div className="table-heading"><div><h2>Guest directory</h2><p>Know the people behind every table.</p></div><div className="filter-search"><Search size={16} /><input placeholder="Search guests" /></div></div><div className="customer-table"><div className="customer-header"><span>Guest</span><span>Visits</span><span>Total spent</span><span>Segment</span><span></span></div>{customers.map((customer) => <div className="customer-row" key={customer.name}><div className="order-guest"><div className="avatar tiny">{customer.name.split(' ').map((n) => n[0]).join('')}</div><span><strong>{customer.name}</strong><small>Last visit · yesterday</small></span></div><strong>{customer.visits}</strong><strong>{customer.spent}</strong><span className="tag-label">{customer.tag}</span><button><MoreHorizontal size={17} /></button></div>)}</div></section><section className="panel customer-side"><div className="side-stat"><UserRound size={18} /><strong>1,284</strong><span>total guests</span></div><div className="side-stat"><HeartIcon /><strong>68%</strong><span>returning guests</span></div><form onSubmit={(e) => { e.preventDefault(); if (name) { setCustomers((c) => [...c, { name, visits: 1, spent: '$0', tag: 'New' }]); setName(''); notify('Guest added'); } }}><h3>Add a guest</h3><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Full name" required /><button className="primary-button" type="submit"><Plus size={16} /> Add guest</button></form></section></div>; }
function HeartIcon() { return <span className="heart-icon">♥</span>; }
function Promotions({ notify }) { const [active, setActive] = useState(true); return <div className="content-grid promo-grid"><section className="panel campaign-list"><PanelHead title="Live campaigns" action="" /><Promo name="Tuesday table" detail="15% off mains · 248 redemptions" active={active} onClick={() => setActive(!active)} color="coral" /><Promo name="Birthday candle" detail="Free dessert · 32 redemptions" active color="plum" /><Promo name="Local love" detail="10% off for neighbors" active color="sage" /><button className="dashed-button" onClick={() => notify('Campaign composer opened')}><Plus size={16} /> Create campaign</button></section><section className="panel campaign-preview"><div className="preview-label">CAMPAIGN PREVIEW</div><div className="promo-hero"><Tag size={22} /><h2>A little more ember.</h2><p>Enjoy 15% off any main course every Tuesday evening.</p><button onClick={() => notify('Offer copied')}>Copy offer code</button></div><div className="preview-stats"><span><strong>248</strong><small>redemptions</small></span><span><strong>$3,740</strong><small>revenue influenced</small></span><span><strong>4.8x</strong><small>return on spend</small></span></div></section></div>; }
function Promo({ name, detail, active = false, onClick, color }) { return <div className="promo-row"><span className={`promo-icon ${color}`}><Tag size={16} /></span><span><strong>{name}</strong><small>{detail}</small></span><button className={`toggle ${active ? 'on' : ''}`} onClick={onClick}><i></i></button></div>; }
function Analytics() { return <div className="stack"><div className="analytics-kpis"><div><span>Gross sales</span><strong>$24,681</strong><small>↑ 14.8% from last week</small></div><div><span>Avg. order value</span><strong>$42.80</strong><small>↑ 6.4% from last week</small></div><div><span>Table turns</span><strong>2.4x</strong><small>↑ 0.3x from last week</small></div></div><div className="content-grid analytics-grid"><section className="panel revenue-panel"><PanelHead title="Sales by daypart" action="This week" /><div className="daypart-bars"><span>Breakfast <i style={{ height: '28%' }}><b>$1.2k</b></i></span><span>Lunch <i style={{ height: '58%' }}><b>$3.8k</b></i></span><span>Dinner <i style={{ height: '88%' }}><b>$8.6k</b></i></span><span>Late night <i style={{ height: '42%' }}><b>$2.1k</b></i></span></div></section><section className="panel"><PanelHead title="Top performers" action="By revenue" /><div className="performers"><Performer rank="01" name="Charred citrus salmon" value="$2,840" width="92%" /><Performer rank="02" name="Ember house burger" value="$2,460" width="78%" /><Performer rank="03" name="Wild mushroom toast" value="$1,930" width="62%" /><Performer rank="04" name="Olive oil cake" value="$1,240" width="44%" /></div></section></div></div>; }
function Performer({ rank, name, value, width }) { return <div className="performer"><span>{rank}</span><div><strong>{name}</strong><i style={{ width }}></i></div><b>{value}</b></div>; }
function Delivery({ notify }) { const [active, setActive] = useState('In transit'); return <div className="content-grid delivery-grid"><section className="panel full-panel"><div className="delivery-map"><div className="map-grid"></div><div className="map-label label-one">Ember Table <span>●</span></div><div className="map-label label-two">River North <span>●</span></div><div className="map-label label-three">Old Town <span>●</span></div><div className="route route-one"></div><div className="route route-two"></div><div className="bike-marker"><Bike size={17} /></div></div><div className="delivery-list">{['#1047 · Amelia Chen', '#1041 · Theo Martin', '#1038 · Priya Shah'].map((name, index) => <div key={name}><div className="avatar tiny">{index === 0 ? 'AC' : index === 1 ? 'TM' : 'PS'}</div><span><strong>{name}</strong><small>{index === 0 ? 'Arriving in 12 min' : 'Picked up 4 min ago'}</small></span><Status value={index === 0 ? active : 'Delivered'} /></div>)}</div></section><section className="panel delivery-side"><PanelHead title="Driver status" action="" /><div className="driver"><div className="avatar large">JL</div><span><strong>Jordan Lee</strong><small>On shift · 4 deliveries</small></span><span className="online"></span></div><button className="quiet-button" onClick={() => notify('Driver message sent')}><Bell size={15} /> Message driver</button></section></div>; }
function SettingsPage({ notify }) { const [toggles, setToggles] = useState({ alerts: true, auto: true, tips: false }); return <div className="settings-layout"><div className="settings-nav"><button className="selected"><Settings size={16} /> General</button><button><Bell size={16} /> Notifications</button><button><ShieldCheck size={16} /> Security</button><button><CreditCard size={16} /> Billing</button></div><section className="panel settings-panel"><h2>General preferences</h2><p>Small details that keep your team in rhythm.</p><label className="setting-row"><span><strong>Service alerts</strong><small>Get a pulse when a ticket needs attention.</small></span><Toggle value={toggles.alerts} onClick={() => setToggles({ ...toggles, alerts: !toggles.alerts })} /></label><label className="setting-row"><span><strong>Auto-advance tickets</strong><small>Move completed kitchen tickets to ready.</small></span><Toggle value={toggles.auto} onClick={() => setToggles({ ...toggles, auto: !toggles.auto })} /></label><label className="setting-row"><span><strong>Suggest gratuity prompts</strong><small>Offer a gentle tip prompt at checkout.</small></span><Toggle value={toggles.tips} onClick={() => setToggles({ ...toggles, tips: !toggles.tips })} /></label><div className="settings-divider"></div><h3>Venue details</h3><div className="form-two"><label>Venue name<input defaultValue="Ember Table" /></label><label>Timezone<select><option>Central Time (US & Canada)</option><option>Eastern Time (US & Canada)</option></select></label></div><button className="primary-button" onClick={() => notify('Preferences saved')}><Check size={16} /> Save changes</button></section></div>; }
function Toggle({ value, onClick }) { return <button className={`toggle ${value ? 'on' : ''}`} onClick={onClick}><i></i></button>; }

export default App;
