name: SMOKE TEST
on: 
    push:
        branches:
            - main 
    workflow_dispatch:
    
permissions:
    contents: read

concurrency:
    group: ./.github/workflows/compose-test.yaml
    cancel-in-progress: false

jobs:
    docker-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - uses: gitleaks/gitleaks-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker Login
              uses: docker/login-action@v4
              with:
                username: ${{ inputs.docker_username }}
                password: ${{ inputs.docker_token }}

            - run: |
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.ANALYTICS_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.CUSTOMER_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.DELIVERY_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.KITCHEN_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.MENU_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.NOTIFICATION_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.ORDER_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.PAYMENT_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.PROMOTION_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.RESERVATION_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.NGINX_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
                docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}

            - name: Start Docker Compose
              uses: hoverkraft-tech/compose-action@b659c744ee9bed25aea2307c017ad849bd104433
              with:
                compose-file: ./docker-compose.yaml
                services: |
                      myreact
                      myngninx
                      analytics-service
                      customer-service
                      delivery-service
                      kitchen-service
                      menu-service
                      notification-service
                      order-service
                      payment-service
                      promotion-service
                      reservation-service"

            - name: Check Services Health
              uses: thegabriele97/dockercompose-health-action@main
              with:
                filename: docker-compose.yaml
                timeout: "60"
                workdir: ./

            - name: Compose Logs
              if: ${{ always() }}
              shell: bash
              run: |
                docker compose -f docker-compose.yaml logsgit remotr 