name: DOCKER BUILD
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:

permissions:
  contents: read

env:
  FRONTEND_IMAGE: myreact
  NGINX_IMAGE: mynginx 
  ANALYTICS_IMAGE: analytics-service
  CUSTOMER_IMAGE: customer-service
  DELIVERY_IMAGE: delivery-service
  KITCHEN_IMAGE: kitchen-service
  MENU_IMAGE: menu-service
  NOTIFICATION_IMAGE: notification-service
  ORDER_IMAGE: order-service
  PAYMENT_IMAGE: payment-service
  PROMOTION_IMAGE: promotion-service
  RESERVATION_IMAGE: reservation-service

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:

          - image: ${{ env.FRONTEND_IMAGE }}
            context: ./
            dockerfile: ./Dockerfile
          - image: ${{ env. }}
            context: ./
            dockerfile: ./Dockerfile.nginx
          - name: analytics
            image: ${{ env. }}
            context: ./services/analytics-service
            dockerfile: ./services/analytics-service/Dockerfile

          - name: customer
            image: ${{ env. }}
            context: ./services/customer-service
            dockerfile: ./services/customer-service/Dockerfile

          - name: delivery
            image: ${{ env. }}
            context: ./services/delivery-service
            dockerfile: ./services/delivery-service/Dockerfile

          - name: kitchen
            image: ${{ env. }}
            context: ./services/kitchen-service
            dockerfile: ./services/kitchen-service/Dockerfile

          - name: menu
            image: ${{ env. }}
            context: ./services/menu-service
            dockerfile: ./services/menu-service/Dockerfile

          - name: notification
            image: ${{ env. }}
            context: ./services/notification-service
            dockerfile: ./services/notification-service/Dockerfile

          - name: order
            image: ${{ env. }}
            context: ./services/order-service
            dockerfile: ./services/order-service/Dockerfile

          - name: payment
            image: ${{ env. }}
            context: ./services/payment-service
            dockerfile: ./services/payment-service/Dockerfile

          - name: promotion
            image: ${{ env. }}
            context: ./services/promotion-service
            dockerfile: ./services/promotion-service/Dockerfile

          - name: reservation
            image: ${{ env. }}
            context: ./services/reservation-service
            dockerfile: ./services/reservation-service/Dockerfile


    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
            fetch-depth: 0

      - name: Generate image tag
        id: tag
        run: |
          IMAGE_TAG="v${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          echo "Image tag: $IMAGE_TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}

          push: true

          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ matrix.image }}:${{ steps.tag.outputs.IMAGE_TAG }}
            ${{ vars.DOCKER_USERNAME }}/${{ matrix.image }}:latest

          cache-from: type=gha
          cache-to: type=gha,mode=max
